### ISSUE TITLE
Could not find 'device_mapper_test_suite' (>= 0)

### ISSUE THREAD

**Issue by simonxu** [jthornber/device-mapper-test-suite#39]
I installed device-mapper-test-suite (5ea215e6b26a44afafafbcec484fda8ee2de6051) following the instructions in README.md.

# which dmtest
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/dmtest

But 'dmtest' fails to run:

# dmtest
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:315:in `to_specs': Could not find 'device_mapper_test_suite' (>= 0) among 38 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/usr/local/rvm/gems/ruby-1.9.3-p551:/usr/local/rvm/gems/ruby-1.9.3-p551@global', execute `gem env` for more information
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:324:in `to_spec'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb:64:in `gem'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/dmtest:22:in `<main>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'

This is 'gem env' output:

# gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.6
  - RUBY VERSION: 1.9.3 (2014-11-13 patchlevel 551) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/rvm/gems/ruby-1.9.3-p551
  - RUBY EXECUTABLE: /usr/local/rvm/rubies/ruby-1.9.3-p551/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/rvm/gems/ruby-1.9.3-p551/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/rvm/rubies/ruby-1.9.3-p551/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/rvm/gems/ruby-1.9.3-p551
     - /usr/local/rvm/gems/ruby-1.9.3-p551@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/rvm/gems/ruby-1.9.3-p551/bin
     - /usr/local/rvm/gems/ruby-1.9.3-p551@global/bin
     - /usr/local/rvm/rubies/ruby-1.9.3-p551/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /root/bin
     - /usr/local/rvm/bin

# ls -1 /usr/local/rvm/gems/ruby-1.9.3-p551/gems/
activemodel-4.2.0
activerecord-4.2.0
activesupport-4.2.0
arel-6.0.0
bigdecimal-1.2.7
builder-3.2.2
bundler-1.8.5
colored-1.2
diff-lcs-1.2.5
ejt_command_line-0.0.4
hoe-3.13.1
i18n-0.7.0
io-console-0.4.2
json-1.8.2
minitest-5.5.1
rake-10.4.2
rdoc-4.2.0
rspec-2.14.0
rspec-core-2.14.8
rspec-expectations-2.14.5
rspec-mocks-2.14.6
ruby-terminfo-0.1.1
test-unit-1.2.3
thinp_xml-0.0.20
thread_safe-0.3.5
tzinfo-1.2.2
webrick-1.3.1

ls -1 /usr/local/rvm/gems/ruby-1.9.3-p551\@global/gems/
bundler-1.8.5
bundler-unload-1.0.2
executable-hooks-1.3.2
gem-wrappers-1.2.7
rake-0.9.2.2
rdoc-3.9.5
rubygems-bundler-1.4.4
rvm-1.11.3.9

Any idea?

**Comment by jthornber** [comment]
Are you running it in the source dir?

**Comment by simonxu** [comment]
No, I didn't.  Running dmtest in the source dir works fine.  Thank you.
