### ISSUE TITLE
cannot load such file -- dmtest/tags (LoadError)

### ISSUE THREAD

**Issue by zhangxiaoxv** [jthornber/device-mapper-test-suite#54]
when I run stacking test suit, can't find dmtest/tags.

device-mapper-test-suite/lib/dmtest/tests/stacking/stacking_tests.rb:8:in `require': cannot load such file -- dmtest/tags (LoadError)

```
[root@localhost device-mapper-test-suite]# dmtest run ssd --suite stacking
Traceback (most recent call last):
	14: from /usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
	13: from /usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
	12: from /usr/local/rvm/gems/ruby-2.5.3/bin/dmtest:23:in `<main>'
	11: from /usr/local/rvm/gems/ruby-2.5.3/bin/dmtest:23:in `load'
	10: from /home/git/device-mapper-test-suite/bin/dmtest:644:in `<top (required)>'
	 9: from /home/git/device-mapper-test-suite/bin/dmtest:632:in `top_level_handler'
	 8: from /home/git/device-mapper-test-suite/bin/dmtest:646:in `block in <top (required)>'
	 7: from /usr/local/rvm/gems/ruby-2.5.3/gems/ejt_command_line-0.0.4/lib/ejt_command_line.rb:178:in `parse'
	 6: from /home/git/device-mapper-test-suite/bin/dmtest:384:in `run'
	 5: from /home/git/device-mapper-test-suite/bin/dmtest:496:in `select_tests'
	 4: from /home/git/device-mapper-test-suite/bin/dmtest:496:in `require'
	 3: from /home/git/device-mapper-test-suite/lib/dmtest/suites/stacking.rb:1:in `<top (required)>'
	 2: from /home/git/device-mapper-test-suite/lib/dmtest/suites/stacking.rb:1:in `require'
	 1: from /home/git/device-mapper-test-suite/lib/dmtest/tests/stacking/stacking_tests.rb:8:in `<top (required)>'
/home/git/device-mapper-test-suite/lib/dmtest/tests/stacking/stacking_tests.rb:8:in `require': cannot load such file -- dmtest/tags (LoadError)
```

**Comment by zhangxiaoxv** [comment]
commit: e62d825cc30a219409a4aef1787891a07c1d51ce
