### ISSUE TITLE
dmtest/command_line (LoadError)

### ISSUE THREAD

**Issue by pahome** [jthornber/device-mapper-test-suite#60]
Hello, 

I cloned project and use master branch, then installed follow the README.md like below

```
git clone device-mapper-test-suite
cd device-mapper-test-suite/
curl -L https://get.rvm.io | bash
rvm install 2.5.3
rvm docs generate-ri
gem update
gem install bundler
bundle update
```

And results are all right.
Then I run `./bin/dmtest list --suite thin-provisioning` and it failed as below:
```
Traceback (most recent call last):
	2: from ./bin/dmtest:5:in `<main>'
	1: from /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dmtest/command_line (LoadError)
```

How to fix that?

**Comment by jthornber** [comment]
I see you posted another issue where you had got it working, so closing this one.
